version: '3.8'

services:
  web:
    build:
      context: .
      target: builder
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src        
      - ./angular:/app        
      - /app/node_modules 